import os
import json
import ollama
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from typing import List
from dotenv import load_dotenv

load_dotenv()

from agent import check_and_run_tools, get_mcp_tools
from logger import log_info, log_error

app = FastAPI(title="GemmaJnana Gateway")

# Enable CORS for the frontend chat client
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

MODEL_NAME = os.getenv("MODEL_NAME", "gemma4:e4b")

class Message(BaseModel):
    role: str
    content: str

class ChatRequest(BaseModel):
    messages: List[Message]
    temperature: float = 0.3
    session_name: str = "default_session"

@app.get("/health")
def health_check():
    try:
        models = [m.model for m in ollama.list().models]
        if any(MODEL_NAME in name for name in models):
            return {"status": "healthy", "model": MODEL_NAME}
        return {"status": "warning", "warning": f"Model {MODEL_NAME} not loaded."}
    except Exception as e:
        return {"status": "unhealthy", "error": str(e)}

@app.get("/tools")
async def get_tools():
    try:
        tools = await get_mcp_tools()
        return tools
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/chat")
async def chat_completion(request: ChatRequest):
    session = request.session_name
    try:
        log_info(session, f"Received chat completion request. Temperature={request.temperature}")
        messages_list = [msg.model_dump() for msg in request.messages]
        log_info(session, f"Message history loaded. Total messages: {len(messages_list)}")
        
        tool_messages = []
        tool_results = {}
        tool_llm_calls = 0

        async for event in check_and_run_tools(messages_list, MODEL_NAME, session):
            if event["type"] == "result":
                tool_messages = event["tool_messages"]
                tool_results = event["tool_results"]
                tool_llm_calls = event["llm_calls"]

        modified_messages = list(messages_list)
        if tool_messages:
            log_info(session, f"Extending history with {len(tool_messages)} tool message(s).")
            modified_messages.extend(tool_messages)

        log_info(session, "[LLM Call] Calling Ollama model for final response...")
        client = ollama.AsyncClient()
        response = await client.chat(
            model=MODEL_NAME,
            messages=modified_messages,
            options={"temperature": request.temperature}
        )
        log_info(session, "Response successfully generated by Ollama.")
        executed_tools = list(tool_results.keys())
        total_llm_calls = tool_llm_calls + 1
        log_info(session, f"Session Summary: Total LLM Calls: {total_llm_calls} | Executed Tool Calls: {executed_tools}")
        return response
    except Exception as e:
        log_error(session, f"Error in chat_completion: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/chat/stream")
async def chat_stream(request: ChatRequest):
    session = request.session_name
    async def event_generator():
        try:
            log_info(session, f"Received chat stream request. Temperature={request.temperature}")
            messages_list = [msg.model_dump() for msg in request.messages]
            log_info(session, f"Message history loaded. Total messages: {len(messages_list)}")
            
            tool_messages = []
            tool_results = {}
            tool_llm_calls = 0

            async for event in check_and_run_tools(messages_list, MODEL_NAME, session):
                if event["type"] == "result":
                    tool_messages = event["tool_messages"]
                    tool_results = event["tool_results"]
                    tool_llm_calls = event["llm_calls"]
                else:
                    # Stream tracer event directly to client UI
                    yield f"data: {json.dumps(event)}\n\n"

            # If any executed tool returned query and results metadata (e.g. search), stream its state to the client
            for tool_res in tool_results.values():
                if isinstance(tool_res, dict) and "query" in tool_res and "results" in tool_res:
                    log_info(session, f"Streaming search state: status=searching, query='{tool_res['query']}'")
                    yield f"data: {json.dumps({'status': 'searching', 'query': tool_res['query']})}\n\n"
                    log_info(session, "Streaming search results state.")
                    yield f"data: {json.dumps({'status': 'results', 'results': tool_res['results']})}\n\n"

            modified_messages = list(messages_list)
            if tool_messages:
                log_info(session, f"Extending history with {len(tool_messages)} tool message(s).")
                modified_messages.extend(tool_messages)

            log_info(session, "[LLM Call] Calling Ollama chat stream...")
            client = ollama.AsyncClient()
            stream = await client.chat(
                model=MODEL_NAME,
                messages=modified_messages,
                stream=True,
                options={"temperature": request.temperature}
            )
            
            chunk_count = 0
            async for chunk in stream:
                content = chunk.message.content
                done = getattr(chunk, "done", False)
                chunk_count += 1
                yield f"data: {json.dumps({'content': content, 'done': done})}\n\n"
                
            log_info(session, f"Stream completed successfully. Sent {chunk_count} chunk(s).")
            executed_tools = list(tool_results.keys())
            total_llm_calls = tool_llm_calls + 1
            log_info(session, f"Session Summary: Total LLM Calls: {total_llm_calls} | Executed Tool Calls: {executed_tools}")
        except Exception as e:
            log_error(session, f"Error in chat_stream event_generator: {e}")
            yield f"data: {json.dumps({'error': str(e)})}\n\n"

    return StreamingResponse(event_generator(), media_type="text/event-stream")

if __name__ == "__main__":
    import uvicorn
    host = os.getenv("GATEWAY_HOST", "127.0.0.1")
    port = int(os.getenv("GATEWAY_PORT", "8435"))
    uvicorn.run(app, host=host, port=port)
